from enum import Enum, auto

class TweakID(Enum):
    # misc pages
    PosterBoard = auto()
    Templates = auto()
    StatusBar = auto()
    Passcode = auto()
    CreateBRFolders = auto()

    # mga
    DynamicIsland = auto()
    SupportsDynamicIsland = auto()
    ModelName = auto()
    BootChime = auto()
    ChargeLimit = auto()
    CollisionSOS = auto()
    TapToWake = auto()
    CameraButton = auto()
    Parallax = auto()
    StageManager = auto()
    iPadOS = auto()
    iPadOSCacheData = auto()
    iPadApps = auto()
    Shutter = auto()
    FindMyFriends = auto()
    Pencil = auto()
    ActionButton = auto()
    InternalStorage = auto()
    InternalInstall = auto()
    SRD = auto()
    AOD = auto()
    AODVibrancy = auto()
    EnableLGLPM = auto()
    DisableLGLPM = auto()
    RdarFix = auto()

    # eligibility
    EUEnabler = auto()
    AIEligibility = auto()
    AIGestalt = auto()
    AIFeatureFlags = auto()
    AIFeatureFlagsUI = auto()
    SpoofModel = auto()
    SpoofHardware = auto()
    SpoofCPU = auto()

    # feature flags
    ClockAnim = auto()
    Lockscreen = auto()
    PhotoUI = auto()
    AI = auto()
    SolariumFFSwiftUI = auto()
    SolariumFFSpringBoard = auto()
    SolariumFFIconServices = auto()
    SolariumFFPhotos = auto()
    SolariumFFDocumentCamera = auto()
    SolariumFFAppleMediaServices = auto()
    SolariumFFSharing = auto()
    SolariumFFMail = auto()
    KioskMode = auto()

    # springboard
    LockScreenFootnote = auto()
    WatchOSCompatibility = auto()
    AirDropDisableTimeLimit = auto()
    SBDontLockAfterCrash = auto()
    SBDontDimOrLockOnAC = auto()
    SBHideLowPowerAlerts = auto()
    SBHideACPower = auto()
    SBNeverBreadcrumb = auto()
    SBShowSupervisionTextOnLockScreen = auto()
    AirplaySupport = auto()
    SBMinimumLockscreenIdleTime = auto()
    SBAlwaysShowSystemApertureInSnapshots = auto()
    HideDICompletely = auto()
    SBShowAuthenticationEngineeringUI = auto()
    UseFloatingTabBar = auto()

    # internal
    SBBuildNumber = auto()
    RTL = auto()
    LTR = auto()
    SBIconVisibility = auto()
    MetalForceHudEnabled = auto()
    iMessageDiagnosticsEnabled = auto()
    IDSDiagnosticsEnabled = auto()
    VCDiagnosticsEnabled = auto()
    AccessoryDeveloperEnabled = auto()
    KeyFlick = auto()

    DisableSecondsHand = auto()
    DisableSearchingWebsites = auto()
    ShowButtonHints = auto()

    AppStoreDebug = auto()
    NotesDebugMode = auto()
    BKDigitizerVisualizeTouches = auto()
    BKHideAppleLogoOnLaunch = auto()
    EnableWakeGestureHaptic = auto()
    PlaySoundOnPaste = auto()
    AnnounceAllPastes = auto()

    # liquid glass
    ForceSolariumFallback = auto()
    DisableSolarium = auto()
    IgnoreSolariumLinkedOnCheck = auto()
    NoLiquidClock = auto()
    NoLiquidDock = auto()
    DisableSpecularMotion = auto()
    DisableOuterRefraction = auto()
    DisableSolariumHDR = auto()

    # risky
    DisableOTAFile = auto()
    CustomResolution = auto()
    # daemons
    Daemons = auto()
    ClearScreenTimeAgentPlist = auto()

    # ── Liquid Glass & Siri – real tweaks ──────────────────────────────────

    # Siri (real Apple MDM managed-preference keys in com.apple.siri.plist)
    Siri2FloatingBubble = auto()    # AssistantEnabled
    Siri2AmbientMode = auto()       # VoiceTriggerEnabled
    Siri2VisualResponse = auto()    # UIAssistantEnabled
    Siri2NaturalVoice = auto()      # KeyboardEnabled
    Siri2OnScreenContext = auto()   # SiriProfanityFilter
    Siri2CallScreening = auto()     # AssistantAllowedForAnyLockscreen

    # Liquid Glass per-app extensions (FeatureFlagTweak → FeatureFlags/Global.plist)
    SolariumFFMessages = auto()
    SolariumFFMaps = auto()
    SolariumFFSafari = auto()
    SolariumFFSpotlight = auto()
    SolariumFFControlCenter = auto()
    SolariumFFNotifications = auto()
    SolariumFFWidgets = auto()
    SolariumFFMusic = auto()
    SolariumFFPodcasts = auto()
    SolariumFFPhone = auto()
    SolariumFFCalendar = auto()
    SolariumFFReminders = auto()
    SolariumFFNotes = auto()

    # Liquid Glass fine-tuning (GlobalPreferences)
    NoLiquidStatusBar = auto()
    NoLiquidNotifications = auto()
    SolariumHighContrast = auto()
    SolariumForceLightTint = auto()
    SolariumMaxBlur = auto()

    # SpringBoard tweaks (com.apple.springboard.plist managed preferences)
    SBAlwaysGlassHeaders = auto()
    SBExpandedDynamicIsland = auto()
    SBShowBatteryPercentageAlways = auto()
    SBHideHomeIndicator = auto()
    SBDisableParallaxEffect = auto()
    SBAlwaysShowClockDI = auto()

    # ── Audio Processing (FeatureFlagTweak → FeatureFlags/Global.plist) ──────
    AudioSpatialDefault = auto()
    AudioEnhancedSpeaker = auto()
    AudioPersonalizedSpatial = auto()
    AudioBackgroundSounds = auto()
    AudioHeadphoneAccom = auto()
    AudioLoudnessNorm = auto()
    AudioSoundEffectsEnabled = auto()
    AudioHapticsSync = auto()

    # ── maxregnerOS: SpringBoard UI Feature Flags ─────────────────────────────
    SBFFFloatingDock = auto()
    SBFFDenseHomeScreen = auto()
    SBFFAppSwitcherV2 = auto()
    SBFFGlassFolders = auto()
    SBFFLiveActivitiesPersistent = auto()
    SBFFAdaptiveGrid = auto()
    SBFFContextWidgets = auto()
    SBFFProximityAnimations = auto()
    SBFFLargeWidgetGrid = auto()
    SBFFDynamicBackground = auto()
    SBFFGlassIconShimmer = auto()
    SBFFPageIndicatorRedesign = auto()
    SBFFEnhancedAppLibrary = auto()
    SBFFGlassSectionDividers = auto()
    SBFFDebugUIOverlay = auto()

    # ── maxregnerOS: UIKit Feature Flags ─────────────────────────────────────
    UIKitFFGlassSheets = auto()
    UIKitFFPillButtons = auto()
    UIKitFFLargeNavHeaders = auto()
    UIKitFFSwipeBackV2 = auto()
    UIKitFFFloatingMenus = auto()
    UIKitFFCardLayouts = auto()
    UIKitFFRubberBandPhysics = auto()
    UIKitFFGlassAlerts = auto()
    UIKitFFCompactProgress = auto()
    UIKitFFHapticKeyboard = auto()
    UIKitFFEnhancedTextRendering = auto()
    UIKitFFDynamicColorAdaptation = auto()

    # ── maxregnerOS: Photos & Camera Feature Flags ────────────────────────────
    PhotosFFEnhancedEditing = auto()
    PhotosFFAIAlbums = auto()
    PhotosFFMemoriesV2 = auto()
    PhotosFFImprovedSearch = auto()
    CameraFFProResVideo = auto()
    CameraFFMacroPro = auto()
    CameraFFNightModePortrait = auto()
    CameraFFProRAWMax = auto()
    CameraFFCinematicV2 = auto()
    CameraFFQuantumHDR = auto()

    # ── maxregnerOS: Messages & FaceTime Feature Flags ────────────────────────
    MsgFFEnhancedSearch = auto()
    MsgFFEffectsV2 = auto()
    MsgFFCollaborativeSharing = auto()
    MsgFFRichLinksV2 = auto()
    FaceTimeFFPersonSegmentation = auto()
    FaceTimeFFReactionAnimations = auto()
    FaceTimeFFSharedPlaybackV2 = auto()
    FaceTimeFFSpatialAudioCall = auto()

    # ── maxregnerOS: Maps & Location Feature Flags ────────────────────────────
    MapsFFImmersiveView = auto()
    MapsFFARWalkDirections = auto()
    MapsFFOfflineEnhanced = auto()
    MapsFFRealtimeTrafficV2 = auto()
    MapsFF3DPlaceCards = auto()
    MapsFFElevationData = auto()

    # ── maxregnerOS: Safari & WebKit Feature Flags ────────────────────────────
    SafariFFEnhancedPrivacy = auto()
    SafariFFTabGroupsV2 = auto()
    SafariFFWebExtensionsAPI = auto()
    SafariFFStartPageRedesign = auto()
    SafariFFFloatingAddressBar = auto()
    SafariFFReaderModeV2 = auto()

    # ── maxregnerOS: Widgets & Live Activities Feature Flags ──────────────────
    WidgetFFInteractiveWidgets = auto()
    WidgetFFLargeFormat = auto()
    WidgetFFAnimatedWidgets = auto()
    LiveActFFPersistentMode = auto()
    LiveActFFGlassPresentation = auto()
    LiveActFFStandbyV2 = auto()

    # ── maxregnerOS: Lock Screen & Notifications Feature Flags ────────────────
    LockFFWidgetsV2 = auto()
    LockFFDepthEffectClock = auto()
    LockFFLiveWeatherBG = auto()
    LockFFAlwaysOnDisplayV2 = auto()
    NotifFFStackedBanners = auto()
    NotifFFGlassNotifications = auto()
    NotifFFQuickRepliesV2 = auto()
    NotifFFSummaryV2 = auto()

    # ── maxregnerOS: System Performance Feature Flags ─────────────────────────
    PerfFFEnhancedLowPower = auto()
    PerfFFBackgroundRefreshV2 = auto()
    PerfFFLowLatencyAudio = auto()
    PerfFFHardwareAcceleration = auto()
    PerfFFThermalStatusUI = auto()
    PerfFFMemoryPressureMonitor = auto()
    PerfFFProcessPriorityBoost = auto()
    PerfFFUltraLowLatencyInput = auto()

    # ── maxregnerOS Exclusive ─────────────────────────────────────────────────
    MaxOSGlassEverywhere = auto()
    MaxOSFluidMotionEngine = auto()
    MaxOSNeuralEngineBoost = auto()
    MaxOSProDisplayRendering = auto()
    MaxOSHyperSmoothScrolling = auto()
    MaxOSChromaticAberration = auto()
    MaxOSDepthSensingV2 = auto()
    MaxOSAmbientIntelligence = auto()
    MaxOSProHapticsEngine = auto()
    MaxOSDynamicIslandPro = auto()

    # ── Haptics, ARKit, Vision, CoreML ────────────────────────────────────────
    HapticsPatternPlayback = auto()
    HapticsAdvancedComposition = auto()
    HapticsSyncedPlayback = auto()
    HapticsAdaptiveTriggers = auto()
    HapticsProEffectsEngine = auto()
    ARKitWorldTrackingV3 = auto()
    ARKitFaceTrackingPro = auto()
    ARKitObjectScanningPro = auto()
    ARKitGeospatialV2 = auto()
    ARKitOcclusionV2 = auto()
    VisionLiveTextV3 = auto()
    VisionDocumentScannerPro = auto()
    VisionSubjectLiftV2 = auto()
    VisionStyleTransferV2 = auto()
    VisionPersonSegV2 = auto()
    CoreMLOnDeviceV2 = auto()
    CoreMLNeuralMaxUtil = auto()
    CoreMLAdaptiveInference = auto()
    CoreMLPrivateCompute = auto()
    CoreMLStreamingInference = auto()

    # ── Network, Bluetooth, Location ──────────────────────────────────────────
    NetHTTP3Default = auto()
    NetQUICEnabled = auto()
    NetAdaptiveQoS = auto()
    NetPrivacyProxyV2 = auto()
    NetLowDataModeV2 = auto()
    BLEEnhancedScanning = auto()
    BLELeAudioCodecs = auto()
    BTCompanionMode = auto()
    BTPersonalHotspotV2 = auto()
    LocPrecisionV2 = auto()
    LocOfflineGeocoding = auto()
    LocBackgroundOptimization = auto()

    # ── CloudKit, iCloud, HealthKit ───────────────────────────────────────────
    CloudKitEncryptionV2 = auto()
    CloudKitSyncPriorityV2 = auto()
    iCloudDriveV2 = auto()
    iCloudKeyValueV2 = auto()
    HealthMentalHealthV2 = auto()
    HealthSleepV3 = auto()
    HealthInsightsV2 = auto()
    HealthCyclingV2 = auto()
    HealthVisionV2 = auto()
    HealthWorkoutV3 = auto()

    # ── Wallet, HomeKit, Focus, ScreenTime ────────────────────────────────────
    WalletCompanionPasses = auto()
    WalletApplePayV3 = auto()
    WalletOrdersV2 = auto()
    WalletIDVerification = auto()
    HomeKitMatterV2 = auto()
    HomeKitAutomationV3 = auto()
    HomeKitEnergyV2 = auto()
    HomeKitCameraV2 = auto()
    FocusContextV2 = auto()
    FocusFiltersV2Extended = auto()
    FocusInsightsV2 = auto()
    ScreenTimeV3 = auto()
    ScreenTimeCommunicationV2 = auto()

    # ── Privacy, Shortcuts ────────────────────────────────────────────────────
    PrivacyAppReportV2 = auto()
    PrivacyLocationV2 = auto()
    PrivacyTrackingV2 = auto()
    PrivacySensorV2 = auto()
    PrivacyDataBrokerV2 = auto()
    ShortcutsV3 = auto()
    ShortcutsAutomationsV2 = auto()
    ShortcutsAIActions = auto()
    ShortcutsAppIntentsV2 = auto()

    # ── Calendar, Contacts ────────────────────────────────────────────────────
    CalSuggestionsV2 = auto()
    CalSmartScheduling = auto()
    CalInsightsV2 = auto()
    CalSharedCalendarV2 = auto()
    ContactsSuggestionsV2 = auto()
    ContactsUnifiedViewV2 = auto()
    ContactsSmartGroupV2 = auto()

    # ── Reminders, Notes, Files ───────────────────────────────────────────────
    RemindersSuggestionsV2 = auto()
    RemindersCollaborationV2 = auto()
    RemindersSmartListsV2 = auto()
    NotesCollaborationV2 = auto()
    NotesSearchV2 = auto()
    NotesTemplatesV2 = auto()
    FilesTaggingV2 = auto()
    FilesSharingV2 = auto()
    FilesQuickLookV2 = auto()

    # ── Gaming, Metal, RealityKit, Media ──────────────────────────────────────
    GameCenterV3 = auto()
    GameMultiplayerV2 = auto()
    MetalRayTracingV2 = auto()
    MetalMLAcceleration = auto()
    RealityKitV3 = auto()
    SpatialComputingV2 = auto()
    MediaTVFloatingPlayer = auto()
    MediaMusicLosslessDefault = auto()
    MediaMusicSpatialDefault = auto()
    MediaPodcastsTranscriptV2 = auto()
    MediaFitnessGroupWorkoutV2 = auto()

    # ── Extended App Feature Flags ────────────────────────────────────────────
    MapsImmersiveViewV2 = auto()
    MapsLookAroundV2 = auto()
    MapsFlyoverV2 = auto()
    MapsTransitV2 = auto()
    MapsGuidesV2 = auto()
    SafariWebCodecAV1 = auto()
    SafariPasskeysFull = auto()
    SafariAdBlockingV2 = auto()
    SafariTranslationV2 = auto()
    SafariWebExtensionsV2 = auto()
    MsgReactionsV2 = auto()
    MsgStickerPacksV2 = auto()
    MsgSharePlayV2 = auto()
    MsgGroupFocusSync = auto()
    MsgCheckInV2 = auto()
    FTHandoffCallsV2 = auto()
    FTVideoMessageV2 = auto()
    FTSpatialFaceTime = auto()
    FTGroupCallsV2 = auto()
    FTPortraitModeCall = auto()
    PhotosSharedLibraryV2 = auto()
    PhotosCleanUpV2 = auto()
    PhotosMemoryMovieV2 = auto()
    PhotosHDRMax = auto()
    PhotosPortraitLightsV2 = auto()
    CameraStudioLightV2 = auto()
    CameraActionModeV2 = auto()
    CameraPhotonicEngineV2 = auto()
    CameraVideoV3 = auto()
    CameraFrontVideoV2 = auto()

    # ── System Core Overrides ─────────────────────────────────────────────────
    SysCoreProMotion = auto()
    SysCoreAnimSpeed = auto()
    SysCoreScrollVelocity = auto()
    SysCoreMTLOverlay = auto()
    SysCoreHideCarrier = auto()
    SysCoreDevSettings = auto()
    SysCoreAlwaysAOD = auto()
    SysCoreNightShiftMax = auto()
    SysCoreAutoRotate = auto()
    SysCoreHDRVideo = auto()

    # ── mROS Kernel Layer (XNU / IOKit / Darwin feature flags) ───────────────
    KernelThreadPriorityBoost = auto()
    KernelMemoryCompression = auto()
    KernelIOSchedulerV2 = auto()
    KernelThermalGovernorV2 = auto()
    KernelCPUGovernorPerf = auto()
    KernelNetworkStackV2 = auto()
    KernelSecureMemoryV2 = auto()
    KernelIRQBalancing = auto()
    KernelZRAMEnabled = auto()
    KernelVMPressureOpt = auto()
    KernelFileSystemCache = auto()
    KernelDiskSchedulerV2 = auto()
    KernelGraphicsDriverV2 = auto()
    KernelAudioDriverV2 = auto()
    KernelUSBStackV2 = auto()
    KernelPowerManagementV2 = auto()
    KernelSecureEnclaveV2 = auto()
    KernelCryptoEngineV2 = auto()
    KernelSandboxV2 = auto()
    KernelSignalHandlerV2 = auto()

    # ── mROS Exclusive V2 — beyond any phone ──────────────────────────────────
    MROSHolographicUI = auto()
    MROSNeuralDisplay = auto()
    MROSQuantumSync = auto()
    MROSBioMetricAura = auto()
    MROSChronoEngine = auto()
    MROSAdaptiveCortex = auto()
    MROSProximityAura = auto()
    MROSRetinalTrack = auto()
    MROSAmbientEngine = auto()
    MROSHyperThread = auto()
    MROSCrystalClear = auto()
    MROSQuantumHaptics = auto()
    MROSNeuralKernel = auto()
    MROSCognitiveUI = auto()
    MROSDeepFusion = auto()
    MROSSilverLining = auto()
    MROSMorphicUI = auto()
    MROSEchoEngine = auto()
    MROSDimensionalShift = auto()
    MROSHyperCore = auto()